language: php
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 7.1
sudo: false
cache:
  directories:
  - $HOME/.composer/cache
before_install:
- composer self-update
- composer install
- composer --version
script:
- echo; echo "Running unit tests"; vendor/bin/phpunit --colors tests/unit
notifications:
  slack:
    secure: vCtEGr91LmiSUBkfCkLYCGYanY6vO1OXaKRDAKGnPiibicuoEZSLlShUy4gTpMKUEAlRCWOFuYR3ueNw/K8cUi6j/sqr+YGo4r2aZlwsXDa5NT9R/QPI0ZngJSvyx9Tl+8/CHpTiZDWjRiCpGegqCyjY26bu5IY8Ng601QF0kIsNDrYXou7hxHde4r4o/Iof2qEUT/LsE0wvLvKiCOAWdaUjwM0BodDK6kxAXrIBnA7jFi+aXSQOqPn5pMEXHP2xJ90fahSb1Hm802TIuSnCmDQeTErrd7B6qQvO+gQq5T1AGwZrrUlceG0QE26D4I68WJb62kjnDhVLrLvq7hbc6WAyLrcMfNZTKc8TuP9a4fLTBRr33g0Rm7tlaAAcCBZ+ezzJ2Ae0xTLyOfKVCW4M55ri8Ltq8/vcJ9np3w7wqtL2b+p2dH81YIDW/Zf9wdZfeOhUSGTyWdyeknxTs6F+Qm6RadPHPqTevNonT7PpSs8epGuX/10jeJ0v+6qHuMpiVXJQjvw+o8hp37tWqWIibArbSgNv8wAJ3MicmgOcX0T+xdnqdpawHWTBrwc908Fp3luFuuCHG8nzK1JnEkwiGtWCvDKc0cw+fjbpf5x0GPTlqyWNmJ8JJpVf/ibyu696+KY7GJ6afEIzsHizP8ph4pnnTtaWrNk+rFjSx/zB+EE=
